apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: apptitude
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: mayur702/apptitude-web-application:backend
        resources:
          limits:
            cpu: "500m"
            memory: "128Mi"
          requests:
            cpu: "250m"
            memory: "128Mi"
        ports:
        - containerPort: 8000