name: Deploy Frontend and Backend to AWS ECS

on:
  push:
    branches:
      - prod  # Trigger workflow on prod branch

jobs:
  deploy:
    name: Deploy Frontend and Backend to Amazon ECS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2  # Change to your AWS region

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Determine Image Tag
        id: image_tag
        run: echo "IMAGE_TAG=v$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Build and Push Frontend Docker Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: apptitude-frontend
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./frontend
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      - name: Build and Push Backend Docker Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: apptitude-backend
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./backend
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      - name: Stop Old ECS Tasks
        env:
          CLUSTER_NAME: apptitude-cluster
        run: |
          TASK_ARNs=$(aws ecs list-tasks --cluster $CLUSTER_NAME --query "taskArns" --output text)
          if [ -n "$TASK_ARNs" ]; then
            aws ecs stop-task --cluster $CLUSTER_NAME --task $TASK_ARNs
          fi

      - name: Deploy Frontend and Backend to Amazon ECS
        env:
          CLUSTER_NAME: apptitude-cluster
          FRONTEND_SERVICE_NAME: apptitude-frontend-service
          BACKEND_SERVICE_NAME: apptitude-backend-service
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          FRONTEND_REPOSITORY: apptitude-frontend
          BACKEND_REPOSITORY: apptitude-backend
          IMAGE_TAG: latest
        run: |
          aws ecs update-service --cluster $CLUSTER_NAME --service $FRONTEND_SERVICE_NAME --force-new-deployment
          aws ecs update-service --cluster $CLUSTER_NAME --service $BACKEND_SERVICE_NAME --force-new-deployment
