name: Terraform Deploy  # This must match in the deploy.yml workflow_run trigger

on:
  push:
    branches:
      - prod
    paths:
      - 'Terraform/**'
      - '.github/workflows/terraform-deploy.yml'

  workflow_dispatch:  #  Allow manual trigger

jobs:
  terraform:
    name: Terraform Deploy
    runs-on: self-hosted

    defaults:
      run:
        working-directory: Terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
